version: '3.9'

services:
  web:
    container_name: web
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.25.0.2
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Wasd123!"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "vstl_data"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      my_network:
        ipv4_address: 172.25.0.5
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
