# Generated by Django 5.0.6 on 2024-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='new', max_length=13),
        ),
    ]
