# Generated by Django 5.0.6 on 2024-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
