# Generated by Django 5.0.6 on 2024-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_blocker',
            name='incorrect_password_counter',
            field=models.IntegerField(default=0),
        ),
    ]
