# Generated by Django 5.0.6 on 2024-07-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0003_remove_password_blocker_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password_blocker',
        ),
    ]
