# Generated by Django 5.0.6 on 2024-07-17 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service_accounts', '0004_delete_password_blocker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password_Blocker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('incorrect_password_counter', models.IntegerField(default=0)),
                ('unlock_date', models.DateTimeField(default='2007-09-23 12:53:42.424242')),
                ('next_blocking_for_how_long', models.IntegerField(default=24)),
            ],
        ),
    ]
